Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -14,23 +14,34 @@ jobs:
         with:
           channel: 'stable'
           architecture: x64
-      - run: flutter pub get
-      
 
+      - run: flutter pub get
+
+      - run: sudo gem install cocoapods
       - run: pod repo update
         working-directory: ios
 
       - run: flutter build ios --release --no-codesign
 
-      - run: mkdir Payload
-        working-directory: build/ios/iphoneos
-
-      - run: mv Runner.app/ Payload
-        working-directory: build/ios/iphoneos
+      - run: |
+          if [ -d "build/ios/iphoneos/Runner.app" ]; then
+            mkdir build/ios/iphoneos/Payload;
+            mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload;
+          else
+            echo "Runner.app not found!";
+            exit 1;
+          fi
 
       - name: Zip output
         run: zip -qq -r -9 FlutterIpaExport.ipa Payload
         working-directory: build/ios/iphoneos
+
+      - name: Verify IPA file
+        run: |
+          if [ ! -f "build/ios/iphoneos/FlutterIpaExport.ipa" ]; then
+            echo "IPA file not found!";
+            exit 1;
+          fi
 
       - name: Upload binaries to release
         uses: svenstaro/upload-release-action@v2
@@ -39,4 +50,4 @@ jobs:
           file: build/ios/iphoneos/FlutterIpaExport.ipa
           tag: v1.0
           overwrite: true
-          body: "This is first release"
+          body: "This is the first release"
